const siteData = {
  meta: {
    baseURL: "https://ashishrokaade.vercel.app",
    keywords: [
      "Ashish Rokade",
      "AI Engineer",
      "Full-stack developer",
      "Next.js",
      "RAG",
      "Agentic AI",
      "Spring Boot",
      "React.js",
    ],
  },
  person: {
    firstName: "Ashish",
    lastName: "Rokade",
    name: "Ashish Rokade",
    role: "AI Engineer & Full-Stack Developer",
    avatar: "/images/avatar.jpg",
    email: "ashishrokade1222@gmail.com",
    phone: "+91 9527631116",
    website: "https://ashishrokaade.vercel.app",
    timezone: "Asia/Kolkata",
    address: "Pune, India",
    languages: ["Hindi", "English", "Marathi"],
    biography:
      "AI Engineer and Full Stack Developer with experience building web applications and AI-powered solutions using Python, Java, JavaScript, REST APIs, and modern AI frameworks. Experienced in Generative AI, Retrieval-Augmented Generation (RAG), agentic workflows, vector databases, prompt engineering, LLM evaluation, and deployment of AI applications.",
  },
  hero: {
    headline: "AI Engineer and Full-Stack Developer building practical web and GenAI products",
    subline: (
      <>
        I build secure full-stack applications, real-time systems, analytics dashboards, and AI workflows using RAG, agent frameworks, REST APIs, and production deployment practices.
      </>
    ),
    featured: {
      label: "GenAI, RAG, React, Node.js, Spring Boot",
      href: "https://www.linkedin.com/in/ashish-rokade-11a609393/",
      badge: "Focus",
    },
    ctaPrimary: {
      label: "View real-time messaging project",
      href: "https://www.linkedin.com/in/ashish-rokade-11a609393/",
    },
    ctaSecondary: {
      label: "",
      href: "",
    },
    stats: [
      { value: "1", label: "Full-stack internship completed" },
      { value: "3", label: "Resume-backed portfolio projects" },
      { value: "4+", label: "Agent and LLM frameworks explored" },
      { value: "2026", label: "B.Tech graduation year" },
    ],
  },
  newsletter: {
    display: false,
    title: "Build log",
    description: "Shipping notes from CodeShare, Beatra, and creator studio automations.",
  },
  social: [
    { name: "GitHub", icon: "github", link: "https://github.com/Ashishr944" },
    { name: "LinkedIn", icon: "linkedin", link: "https://www.linkedin.com/in/ashish-rokade-11a609393/" },
    { name: "LeetCode", icon: "leetcode", link: "https://leetcode.com/u/AshishRokade12/" },
    { name: "Twitter", icon: "twitter", link: "" },
    { name: "Instagram", icon: "instagram", link: "https://www.instagram.com/ashish.rokade_/" },
    { name: "YouTube", icon: "youtube", link: "" },
    { name: "Telegram", icon: "telegram", link: "" },
    { name: "Discord", icon: "discord", link: "" },
    { name: "Email", icon: "email", link: "mailto:ashishrokade1222@gmail.com" },
  ],
  about: {
    introTitle: "Who I am",
    introDescription:
      "I am an AI Engineer and Full-Stack Developer with hands-on experience building web applications and AI-powered solutions. My work spans React, Node.js, Express, Java, Spring Boot, Python, REST APIs, databases, Docker-based deployments, RAG pipelines, prompt engineering, LLM evaluation, and agentic workflows.",
    experiences: [
      {
        company: "AB Infotech Solution Pvt Ltd",
        timeframe: "Jan 2026 - May 2026",
        role: "Full Stack Developer Intern - Pune, Hybrid",
        achievements: [
          "Developed a Smart Watch Monitoring & Data Analytics Web Application using Java, Spring Boot, MySQL, HTML, CSS, and JavaScript to track health metrics through an interactive dashboard.",
          "Designed and implemented core modules including authentication, dashboard management, CRUD operations, and responsive UIs to improve data accessibility.",
          "Built and integrated RESTful APIs for seamless frontend-backend communication and optimized application workflows.",
          "Managed MySQL relational schemas, created optimized SQL queries, and structured data operations for secure storage and processing.",
          "Performed debugging, software testing, API validation, and issue resolution using Postman and Chrome DevTools.",
          "Participated in requirement discussions, stakeholder interactions, requirement clarification activities, and software development life cycle processes.",
          "Contributed to documentation activities including API and technical documentation.",
          "Worked with Git/GitHub workflows, deployment processes, bug fixing, and maintenance of application modules.",
        ],
        images: [],
        link: "",
      },
      {
        company: "Additional AI Experience",
        timeframe: "2025 - Present",
        role: "AI Application Builder",
        achievements: [
          "Built Generative AI applications using Large Language Models (LLMs) and agent-based workflows.",
          "Worked with Retrieval-Augmented Generation (RAG) architectures involving embeddings, semantic search, and vector databases.",
          "Used agent frameworks including LangGraph, CrewAI, AutoGen, and LangChain Agents.",
          "Applied prompt engineering techniques and LLM evaluation approaches for AI application development.",
          "Utilized cloud platforms and Docker-based environments for AI solution deployment and testing.",
          "Worked with observability and monitoring practices to support AI application reliability.",
        ],
        images: [],
        link: "",
      },
    ],
    studies: [
      {
        name: "B.Tech - Computer Science and Design",
        description:
          "Maharashtra Institute of Technology, CSN. 2022 - 2026. CGPA: 6.78 / 10.0.",
      },
    ],
    technical: [
      {
        title: "AI & GenAI",
        description: "RAG, agents, evaluation",
        images: [],
        tags: [
          { name: "Generative AI" },
          { name: "RAG" },
          { name: "Agentic AI Workflows" },
          { name: "Prompt Engineering" },
          { name: "LLM Evaluation" },
          { name: "LangGraph" },
          { name: "CrewAI" },
          { name: "AutoGen" },
          { name: "LangChain Agents" },
          { name: "Embeddings" },
          { name: "Semantic Search" },
          { name: "Vector Databases" },
        ],
      },
      {
        title: "Frontend Development",
        description: "Responsive interfaces",
        images: [],
        tags: [
          { name: "React.js" },
          { name: "Next.js" },
          { name: "JavaScript", icon: "javascript" },
          { name: "HTML5" },
          { name: "CSS3" },
          { name: "Tailwind CSS" },
          { name: "Chart.js" },
        ],
      },
      {
        title: "Backend & APIs",
        description: "Services and auth",
        images: [],
        tags: [
          { name: "Java" },
          { name: "Spring Boot" },
          { name: "Node.js" },
          { name: "Express.js" },
          { name: "Python" },
          { name: "FastAPI" },
          { name: "Django" },
          { name: "Flask" },
          { name: "REST APIs" },
          { name: "JWT" },
          { name: "RBAC" },
        ],
      },
      {
        title: "Database, Cloud & Tools",
        description: "Deployments and workflow",
        images: [],
        tags: [
          { name: "MySQL" },
          { name: "PostgreSQL" },
          { name: "MongoDB" },
          { name: "Prisma" },
          { name: "AWS" },
          { name: "Azure" },
          { name: "GCP" },
          { name: "Docker" },
          { name: "Git", icon: "github" },
          { name: "GitHub", icon: "github" },
          { name: "GitLab" },
          { name: "CI/CD" },
          { name: "Postman" },
          { name: "Jira" },
          { name: "Confluence" },
          { name: "Render" },
        ],
      },
    ],
  },
  gallery: [
    "/images/projects/pallawankur_nursery.png",
    "/images/projects/spm.png",
    "/images/projects/vera_bot.png",
    "/images/projects/endless_runner.png",
    "/images/projects/Pallawankur.jpg",
  ],
  github: {
    username: "Ashishr944",
    highlight: [
      "vera-bot",
      "spm",
      "endless-runner",
      "Portfolio-of-Ashish-Rokade",
    ],
    description:
      "Open source projects by Ashish Rokade, including full-stack applications, real-time messaging, academic analytics, AI experiments, and browser-based interactive experiences.",
  },
};

export default siteData;
